### ISSUE TITLE
Failing silently on some .scss files

### ISSUE THREAD

**Issue by bbodien** [dmnsgn/sublime-stylefmt#15]
When I run the Sublime `Run Stylefmt` command in some of my .scss files, no changes are made and the command seems to fail silently (nothing in the console, no error popups). It works fine in others, and when I run stylefmt from the command line on the same files, it makes changes to all of them. One example file where `Run Stylefmt` does nothing is here: http://b.ntrn.cc/173C2h0v2T2s

**Comment by dmnsgn** [comment]
The problem comes from these lines:
```scss
.travel-comparison-grid {
  -webkit-overflow-scrolling: touch;

  // TODO: This isn't working properly. Check Polyfill in Chrome

  // @include prefixer(scroll-snap-type, mandatory, webkit moz spec);
  // @include prefixer(scroll-snap-destination, 1 100%, webkit moz spec);
  // @include prefixer(scroll-snap-points-x, repeat(195px), webkit moz spec);
}
```
 It works well with the CLI indeed... which don't makes sense since the same version ([4.3.1](https://github.com/morishitter/stylefmt/releases)) is used.
