### ISSUE TITLE
stylefmt automatically adds new line after block? #326

### ISSUE THREAD

**Issue by craigcosmo** [dmnsgn/sublime-stylefmt#24]
my stylelint rule in stylelint.rc

```json
{
	"plugins": [
		"stylelint-scss"
	],
	"rules": {
		"function-calc-no-unspaced-operator":true,
		"function-linear-gradient-no-nonstandard-direction":true,
		"string-no-newline":true,
		"unit-no-unknown":true,
		"property-no-unknown":true,
		"keyframe-declaration-no-important":true,
		"block-no-empty":true,
		"indentation": "tab",
		"selector-pseudo-class-no-unknown":[true, {"ignorePseudoClasses": ["global"]}],
		"selector-pseudo-element-no-unknown":true,
		"selector-type-no-unknown":true,
		"media-feature-name-no-unknown":true,
		"at-rule-no-unknown":true,
		"comment-no-empty":true,
		"color-no-invalid-hex":true,
		"font-family-no-duplicate-names":true,
		"no-empty-source":true,
		"no-extra-semicolons":true,
		"no-unknown-animations":true,
		"declaration-block-no-duplicate-properties": true,
		"no-duplicate-selectors": true
	}
}
```

When I run stylelint fmt

it turns my original code
```css
	.neo {
		width: 100%;
	}
	.kiu {
		padding-top: 80px;
	}
```
to this

```css
	.neo {
		width: 100%;
	}
	
	.kiu {
		padding-top: 80px;
	}
```

There is a new new after `.neo` block in the formatted result. Even though I didn't set any rule about new line after block.
